name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install numpy scipy scikit-learn pandas tensorflow joblib pytest
        conda install imageio scikit-image
        conda install -c conda-forge dlib
        pip install markdown
        pip install -e  .
        pytest -sv

  armv64_job:
      name: Build and Test for arm64
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1
        - name: Install and Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              arm64v8/ubuntu:20.04 \
              bash -exc 'apt-get update && apt-get -y install python3 python3-pip python3-venv curl wget && \
              python3 -m pip install virtualenv && python3 -m venv py38-venv && \
              source py38-venv/bin/activate && \
              wget -q "https://github.com/conda-forge/miniforge/releases/download/4.8.2-1/Miniforge3-4.8.2-1-Linux-aarch64.sh" -O miniconda.sh && \
              chmod +x miniconda.sh && \
              ./miniconda.sh -u -b -p $HOME/miniconda3 && \
              export PATH=$HOME/miniconda3/bin:$PATH && \
              ~/miniconda3/bin/conda install conda-build -y && \
              ~/miniconda3/bin/conda create -q -y --name testenv python=3.8 cython numpy pytest psutil pip && \
              source ~/miniconda3/bin/activate testenv && \
              conda env update --file environment.yml --name base
              conda install flake8
              flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
              flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
              conda install numpy scipy scikit-learn pandas tensorflow joblib pytest
              conda install imageio scikit-image
              conda install -c conda-forge dlib
              pip install markdown
              pip install -e  .
              pytest -sv
              deactivate'
